### ISSUE TITLE
Malware Related Request

### ISSUE THREAD

**Issue by Ijaja** [ritchielawrence/cmdow#1]
Hello Richie.

I like cmdow and am going to integrate it in my tool. To be save not to scare any customer i would like to avoid any problem with an anti-virus vendor. Due to the fact, that i do not need the hide window feature, can you remove it in a simple way such that no problem with any vendor will occure?
I experienced this problem myself, when i first downloaded the binary: Before i recognized what happend, the virus scanner removed the binary.

Best regards

**Comment by ritchielawrence** [comment]
Hello Ijaja,

You can remove the hide window feature yourself. Here's how:-

- Download and install [CodeBlocks IDE](http://codeblocks.org)
- Download/extract lastest version of Cmdow
- Open the project file (cmdow.cbp)
- Edit wlist.cpp and comment out this line "ShowWindowAsync(w->hwnd, SW_HIDE);" (line 423 in version 1.4.8
- Build the project (Ctrl-F9)
- This will create a new .\bin\Release\cmdow.exe

I just tried this and submitted the new file to [VirusTotal](https://virustotal.com/en/file/910e51198b6f3d7d981e4b6814a0b6ee1f32635a98e509cf5d0659652078b98e/analysis/1470664374/).

**Comment by drescherjm** [comment]
I use cmdow.exe in a Qt based software to allow me to manipulate the position of windows from different applications my software launches to view medical images for research purposes. It's so annoying to me that so many anti-virus vendors false detect cmdow.exe as a potential virus / malware since it causes me extra work and I also have to convince IT and external organizations that my software is not malicious.
